a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
print("*******comparision operators*******")
print("Is equals:",a==b)
print("Is not equals:",a!=b)
print("Greater than:",a>b)
print("Less than:",a<b)
print("Less than equals:",a<=b)
print("Greater than equals:",a>b)
